spring:
  application:
    name: expense-tracking
  datasource:
    url: jdbc:postgresql://localhost/expense_tracking
    username: sethon
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
